### ISSUE TITLE
Page breaks if no video available

### ISSUE THREAD

**Issue by lugspain** [lugspain/portal#10]
Hey @Stephy6 
I see a minor bug here:
- try to navigate from homepage to [[La DEVCON desde tu casa con la gente de la comunidad](http://localhost:3000/event/276401889)](http://localhost:3000/event/276401889)
- As there's no Youtube vide, I guess, the page component breaks

Do you mind to take a look?
Thanks!

1
![image](https://user-images.githubusercontent.com/106336918/190872925-c4263959-05c7-4417-8a96-7074d7207df2.png)

2
![image](https://user-images.githubusercontent.com/106336918/190872940-562b63d5-14b9-4ed5-bf4b-950566f77c36.png)

Console output
![image](https://user-images.githubusercontent.com/106336918/190872946-d52c1a93-792e-4f9f-af89-6b66f78c8475.png)

**Comment by beltranrengifo** [comment]
Done!
